### PR TITLE
Introduce writeEndpoint to allow resource actions

### LINKED ISSUE #141: Add support for resource actions
As discussed in https://github.com/json-api/json-api/issues/320, the `JSON:API` standard lacks a specification on how resource actions should be handled. Until it's settled I propose that `redux-json-api` implements a `writeEndpoint` actionCreator similar to `readEndpoint` but as a POST request, which makes it up to the developer how to handle the semantics regarding resource actions.

I argue that this should be implemented, so that developers do not have to setup another client with headers, authentication, etc. when the `redux-json-api` client is already present.

### PR DESCRIPTION
**Pull request by mathiasjakobsen**
Similar to `readEndpoint` but POSTs instead, and allows a body in the request. This makes it possible to use the already setup client, to call actions like:

```ruby
POST https://app.io/api/:resource/:id/actions/:action
```

Resolves #141

### CODE REVIEW

**Comment by mathiasjakobsen** [comment]
If the Pull Request is accepted, I'll be happy to provide the documentation as well.

**Comment by egeriis** [comment]
Thank you for the PR @mathiasjakobsen 

We require a broken test to be added before new features are implemented. Please add this to the PR.

Considering that it's not in the JSON API spec, I am having a hard time justifying adding this functionality. So a functionality I think would make sense, is one where we implement a proxy to allow easy execution of requests that automatically includes authorization and other headers to be included. So basically a proxy to a complete call to `apiRequest`.

What are your thoughts?

**Comment by mathiasjakobsen** [comment]
After some consideration I actually concur. But I do think that JSON:API is missing a specification on how to trigger actions, and not just CRUD on entities. I also considered the proxy way of doing it, but opted for the above for the sake of consistency.

The project I was working on actually pivoted, and we wanted to try GraphQL, so I'm not going to need the change myself - but I still think it's a thing that should be implemented somehow.

**Comment by egeriis** [comment]
We'll leave this closed for now.

**Pull request closed without merging**
