### PR TITLE
Adding API Playground

### PR DESCRIPTION
**Pull request by Nopzen**
# Adding a API Testing grounds.
### What is this?

This will add a small small setup where a user can test the API, and try to see how responses are handled.
### Whats missing
- [ ] Better styling demo
- [ ] Host / Build Process.
- [ ] Patch Request
- [ ] Documentation to setup the test & run it.

### CODE REVIEW

**Comment by evolve2k** [comment]
@nopzen looks interesting :) If we want to have a play with this, can I give a few tips on how to get started.

**Comment by evolve2k** [comment]
Woops, just re-read what I said I mean to say "Can *you give us* a few tips on how to get started". Soz that came across wrong. Must be writing stuff too late at night ;)

**Comment by Nopzen** [comment]
@evolve2k hehe Thats okay, basicly its just a simple frontend interface the people who are looking into this tool can see how it works :) 

Alternatively they could replace the dev server proxy to a development server and then add their own test calls :) So its basicly just to give a simple demo of how the tool handles the data.

**Comment by evolve2k** [comment]
@Nopzen I've had a play around with this, and attempted to start a README on how to get started. 
Think it will be be too hard to make as a _pull request of a pull request_ for the moment, so I'll just include the details here. 

Mostly guesswork on my part.. How does this look?

How to use the API Example Server
==========================

This is a local API you can use to test the API, and try to see how responses are handled.

#### Getting started

Clone this repository locally, then open the 'example' directory and run the following:

    $ npm install

#### Get the API server running so it's ready to take requests:

    $ node api/server.js

#### Get the Client up and running

Open a separate terminal window and start client front end you can use to play with the server:

    $ node dist/index.js

**Comment by evolve2k** [comment]
Personally when I ran `node dist/index.js` I got this:
```
⚡ node dist/index.js
DEmo:)
/Users/user/projects/github/redux-json-api/example/dist/index.js:56
	_reactDom2.default.render('Goodbye World', document.getElementById('root'));
	                                           ^

ReferenceError: document is not defined
    at Object.<anonymous> (/Users/user/projects/github/redux-json-api/example/dist/index.js:56:45)
...
```

**Comment by Nopzen** [comment]
Try go to folder `src` and run `$ npm start` then it should work? :)

**Comment by Nopzen** [comment]
Ill be closing this, way over due in favor of #99

**Pull request closed without merging**
