### PR TITLE
Allow `include` URL parameter

### PR DESCRIPTION
**Pull request by hoverlover**
This PR will allow us to create a resource and have the associated relationships included in the response, like this:

```http
POST /articles?include=author HTTP/1.1
Accept: application/vnd.api+json

{
  "data": {
    "type": "articles",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "9" }
      }
    }
  }
}

HTTP/1.1 201 Created
Location: http://example.com/articles/550e8400-e29b-41d4-a716-446655440000
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "articles",
    "id": "550e8400-e29b-41d4-a716-446655440000",
    "attributes": {
      "title":  "JSON API paints my bikeshed!"
    },
    "links": {
      "self": "http://example.com/articles/550e8400-e29b-41d4-a716-446655440000"
    },
    "included": [
      {
        "id": "ab0c375c-10b6-11e7-93ae-92361f002671",
        "type": "people",
        "links": {
          "self": "http://example.com/people/14172380274"
        },
        "attributes": {
          "first-name": "Steve",
          "last-name": "Vai"
        }
      }
    ]
  }
}
```

There is a new `setIncludeParam` action creator that handles this, and it can also be used for the `readEntity` API method as an alternative to specifying it as part of the `endpoint` argument.

See this [discussion](http://discuss.jsonapi.org/t/can-we-include-documents-in-a-post/867) for relevance.

### CODE REVIEW

**Comment by hoverlover** [comment]
Also, I did not break the build :)   Those 3 failing specs were already broken on master.

**Comment by egeriis** [comment]
This is great, @hoverlover. I am in doubt about the method to set include params though. 

Wouldn't it be more flexible to allow include params to be specified in an options object, when calling `createResource` or `updateResource`? I.e. `dispatch(createResource({ type: 'person', ... }, { include: 'comments' }))`

**Comment by hoverlover** [comment]
@egeriis I honestly can't remember why I used a method to set the include params.  It's been too long ago :)  I do like your approach, though, so I will explore it and if it works out I will open a new PR.

**Comment by egeriis** [comment]
This will become possible with #148

**Pull request closed without merging**
